services:
  db:
    image: mariadb:10.5
    volumes:
      - type: bind
        source: ${DB_BIND_DIR}
        target: /var/lib/mysql

  web:
    # build: .
    image: lsstdesc/docdb
    container_name: docdb-storage
    environment:
      DB_NAME: ${DB_NAME}
      DB_RWUSER: ${DB_USER}
      DB_ROUSER: ${DB_USER}
      DB_RWPASSWORD: ${DB_RWPASSWORD}
      DB_ROPASSWORD: ${DB_ROPASSWORD}
      SERVER_URL: http://localhost:8081
    depends_on:
      - db
    ports:
      - "8081:8080"
    stdin_open: true
    tty: true
