version: "3.5"
services:
  db:
    image: mariadb:10.5
    volumes:
      - docdb-mariadb:/var/lib/docdb

  web:
    build: .
    # image: lsstdesc/docdb
    container_name: docdb-storage
    environment:
      DB_NAME: ${DB_NAME}
      DB_RWUSER: ${DB_USER}
      DB_ROUSER: ${DB_USER}
      DB_RWPASSWORD: ${DB_RWPASSWORD}
      DB_ROPASSWORD: ${DB_ROPASSWORD}
      SERVER_URL: https://portal.lsst-desc.org
    depends_on:
      - db
    volumes:
      - /sdf/group/desc/docdb/volumes/docdb:/var/lib/docdb
    ports:
      - "8999:8080"

volumes:
  docdb-mariadb:

version: '3.4'
