version: "3.5"
services:
  db:
    image: mariadb:10.5
    restart: always
    volumes:
      - docdb-mariadb:/var/lib/mysql

  web:
    build: .
    # image: lsstdesc/docdb
    container_name: docdb-storage
    restart: always
    user: "${UID}:${GID}"
    environment:
      DB_NAME: ${DB_NAME}
      DB_RWUSER: ${DB_USER}
      DB_ROUSER: ${DB_USER}
      DB_RWPASSWORD: ${DB_RWPASSWORD}
      DB_ROPASSWORD: ${DB_ROPASSWORD}
      SERVER_URL: https://portal.lsst-desc.org
      DOCDB_USER: ${DOCDB_USER}
      DOCDB_USER_PASSWORD: ${DOCDB_USER_PASSWORD} 
      DOCDB_ADMIN_USER: ${DOCDB_ADMIN_USER}
      DOCDB_ADMIN_PASSWORD: ${DOCDB_ADMIN_PASSWORD} 

    depends_on:
      - db
    volumes:
      - /var/lib/docdb:/var/lib/docdb:z
      - /sdf/home/b/bvan/docdb-deploy/ProjectRoutines.pm:/var/www/cgi-bin/DocDB/ProjectRoutines.pm
    ports:
      - "8999:8080"

volumes:
  docdb-mariadb:
    external: true

version: '3.4'
